### ISSUE TITLE
static/log.txt

### ISSUE THREAD

**Issue by tvilberg** [shrocky2/SiriGarage#6]
I installed SiriGarage and have verified that the relay and the sensor (1) for door 1 are working.  

I am having some difficulty saving new Settings, and when I run the program I get the following…

**********
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pi/SiriGarage/siriweb.py", line 122, in index
    logfile = open("static/log.txt","a")
FileNotFoundError: [Errno 2] No such file or directory: 'static/log.txt'
*******

There is a file “log.txt” in a folder “static” in SiriGarage.   I’m running it from the /home/pi location (though I get the same error if I install it in /root.  I haven't mucked around in flask yet, but that’s where I’m headed.

**Comment by shrocky2** [comment]
the first thing i would try would be to change line 122 that says logfile = open("static/log.txt","a")....change the path listed to the full path, you may need to change similar lines too, like 128 and 404.

Change to:
logfile = open("/home/pi/SiriGarage/static/log.txt","a")

let me know if that fixes your problem.

**Comment by tvilberg** [comment]
That fixed part of the problem. 

Now the relay operates on button and the sensor gets the door status correctly.  

What doesn’t work is any change in the settings via the web interface.  Nothing sticks after reboot. 

I should mention that I’m running Raspbian Lite and doing testing with Siri “Off”. 


Regards,
Tom Vilberg

**Comment by shrocky2** [comment]
Sounds like its another issue locating the file to save the configuration file. Line 286 says: 	
ConfigFile = open("config.py", "w")

Change that to include the file location:
ConfigFile = open("/home/pi/SiriGarage/static/config.py", "w")

If this doesn't work, you can always open the config.py file with the nano app and change your settings there.
sudo nano config.py

(Also make sure you are running the program using the "sudo" command.)

**Comment by tvilberg** [comment]
I’m away from that computer on holiday just now, but will try again in several weeks. 

I have run the program through sudo, and have taken to editing the config.py to more immediately and reliably induce config changes. So there is that. 

I should also mention that I’ve been running Raspbian Lite, if that mattered. 

Anyway, thanks for the vigilance and support.  I look forward to resolving the remaining issues on my return. 

Regards,
Tom Vilberg
